import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Delivery Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Food Delivery</h1>

        <p className={styles.description}>
          Get started by editing <br />
          <a className={styles.code} href="/category" style={{ margin: "5px" }}>
            Category
          </a>
          <a className={styles.code} href="/food" style={{ margin: "5px" }}>
            Food
          </a>
          <a className={styles.code} href="/users" style={{ margin: "5px" }}>
            Users
          </a>
        </p>
      </main>
    </div>
  );
};

export default Home;
